# Generated by Django 5.2.14 on 2026-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_app', models.CharField(max_length=200, verbose_name='Nombre de la app')),
                ('categoria', models.CharField(choices=[('Juegos', 'Juegos'), ('Social', 'Social'), ('Productividad', 'Productividad'), ('Educación', 'Educación'), ('Entretenimiento', 'Entretenimiento'), ('Herramientas', 'Herramientas'), ('Fotografía', 'Fotografía')], max_length=50, verbose_name='Categoría')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Calificación (0-5)')),
                ('descargas', models.CharField(max_length=50, verbose_name='Descargas aprox.')),
                ('reseña', models.TextField(verbose_name='Reseña del usuario')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Reseña de App',
                'verbose_name_plural': 'Reseñas de Apps',
                'ordering': ['-calificacion'],
            },
        ),
    ]
